# Generated by Django 2.1.5 on 2019-05-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('laboratory', models.CharField(max_length=200, verbose_name='Лаборатория')),
                ('result', models.TextField(verbose_name='Резултат')),
                ('priority', models.TextField(verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Assistent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport', models.TextField(unique=True, verbose_name='Паспортные данные')),
                ('telephone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('work_plan', models.TextField(null=True, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Лаборант',
                'verbose_name_plural': 'Лаборанты',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport', models.TextField(unique=True, verbose_name='Паспортные данные')),
                ('telephone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('work_plan', models.TextField(null=True, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Кассир',
                'verbose_name_plural': 'Кассиры',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.Assistent', verbose_name='Лаборант')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('major', models.TextField(verbose_name='Специальность')),
                ('passport', models.TextField(unique=True, verbose_name='Паспортные данные')),
                ('telephone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('work_plan', models.TextField(null=True, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('image', models.CharField(max_length=100, unique=True, verbose_name='Ссылка на фото')),
                ('title_information', models.TextField(verbose_name='Оглавление')),
                ('full_information', models.TextField(verbose_name='Полный текст')),
            ],
            options={
                'verbose_name': 'Медицина',
                'verbose_name_plural': 'Медицины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('assistent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Assistent', verbose_name='Лаборант')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MedSister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport', models.TextField(unique=True, verbose_name='Паспортные данные')),
                ('telephone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('work_plan', models.TextField(null=True, verbose_name='График работы')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.Doctor', verbose_name='Медсестра')),
            ],
            options={
                'verbose_name': 'Медсестра',
                'verbose_name_plural': 'Медсестры',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='OutPatientCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_police', models.CharField(max_length=30, unique=True, verbose_name='Номер страх. полиса')),
                ('passport', models.TextField(unique=True, verbose_name='Паспортные данные')),
                ('company', models.CharField(max_length=50, verbose_name='Страх. компания')),
                ('record', models.TextField(verbose_name='Записи')),
            ],
            options={
                'verbose_name': 'Амбулаторная карта',
                'verbose_name_plural': 'Амбулаторные карты',
                'ordering': ['number_police'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('муж', 'Муж'), ('жен', 'Жен')], max_length=5, verbose_name='Пол')),
                ('telephone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('birthday', models.DateField()),
                ('blood_group', models.CharField(choices=[('-1', '-1'), ('-2', '-2'), ('-3', '-3'), ('-4', '-4'), ('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4')], max_length=5, verbose_name='Группа крови')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время приема')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='RegistryClerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport', models.TextField(unique=True, verbose_name='Паспортные данные')),
                ('telephone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('work_plan', models.TextField(null=True, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Ригистратор',
                'verbose_name_plural': 'Ригистраторы',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('diagnose', models.TextField(verbose_name='Диагноз')),
                ('medication', models.TextField(verbose_name='Лечение')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Doctor', verbose_name='Врач')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.OutPatientCard', verbose_name='Амбулаторная карта')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('number', models.IntegerField(verbose_name='Количество посещений')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Cashier', verbose_name='Кассир')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='reception',
            name='registrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.RegistryClerk', verbose_name='Регистратор'),
        ),
        migrations.AddField(
            model_name='outpatientcard',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='medrequest',
            name='medsister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.MedSister', verbose_name='Медсестра'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medicina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Medicina', verbose_name='Медицина'),
        ),
        migrations.AddField(
            model_name='contract',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.Doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='contract',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='assistent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Assistent', verbose_name='Лаборант'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.Doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='out_patient_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.OutPatientCard', verbose_name='Амбулаторная карта'),
        ),
    ]
