# Generated by Django 2.1.5 on 2019-05-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20190512_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrequest',
            name='assistent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_request', to='mainApp.Assistent', verbose_name='Лаборант'),
        ),
        migrations.AlterField(
            model_name='medrequest',
            name='medsister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_request', to='mainApp.MedSister', verbose_name='Медсестра'),
        ),
        migrations.AlterField(
            model_name='outpatientcard',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out_patient_card', to='mainApp.Patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='mainApp.Cashier', verbose_name='Кассир'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='mainApp.Doctor', verbose_name='Врач'),
        ),
    ]
