# Generated by Django 2.1.5 on 2019-05-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20190512_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGrafic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.CharField(choices=[(0, 'Выходной'), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=20, verbose_name='Понедельник начало работы')),
                ('monday_stop', models.CharField(choices=[(0, 'Выходной'), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=20, verbose_name='Понедельник начало работы')),
                ('tuesday_start', models.CharField(choices=[(0, 'Выходной'), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=20, verbose_name='Вторник начало работы')),
                ('wednesday_start', models.CharField(choices=[(0, 'Выходной'), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=20, verbose_name='Среда начало работы')),
                ('thursday_start', models.CharField(choices=[(0, 'Выходной'), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=20, verbose_name='Четверг начало работы')),
                ('friday_start', models.CharField(choices=[(0, 'Выходной'), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=20, verbose_name='Пятница начало работы')),
                ('saturday_start', models.CharField(choices=[(0, 'Выходной'), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=20, verbose_name='Суббота начало работы')),
                ('weekend_one_people_start', models.TextField(null=True, verbose_name='Отпуск начало (дд.мм.гг)')),
                ('weekend_one_people_stop', models.TextField(null=True, verbose_name='Отпуск конец (дд.мм.гг)')),
                ('weekend', models.TextField(null=True, verbose_name='Выходные дни (дд.мм)')),
            ],
        ),
        migrations.AlterField(
            model_name='assistent',
            name='work_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.WorkGrafic', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='work_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.WorkGrafic', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='work_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.WorkGrafic', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='medsister',
            name='work_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.WorkGrafic', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='registryclerk',
            name='work_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.WorkGrafic', verbose_name='График работы'),
        ),
    ]
