# Generated by Django 2.1.5 on 2019-05-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20190512_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgrafic',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графикы работы'},
        ),
    ]
