# Generated by Django 2.1.5 on 2019-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20190512_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterField(
            model_name='reception',
            name='registrator',
            field=models.CharField(max_length=225, null=True, verbose_name='Регистратор'),
        ),
    ]
