# Generated by Django 2.1.5 on 2019-05-13 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20190512_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.CharField(max_length=100, verbose_name='Ссылка на фото')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('medicina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='mainApp.Medicina', verbose_name='Услуги')),
            ],
        ),
        migrations.AlterField(
            model_name='analysis',
            name='assistent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyse', to='mainApp.Assistent', verbose_name='Лаборант'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyse', to='mainApp.Doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medicina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='mainApp.Medicina', verbose_name='Медицина'),
        ),
    ]
