# Generated by Django 2.1.5 on 2019-05-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20190513_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicina',
            options={'ordering': ['name'], 'verbose_name': 'Медицина', 'verbose_name_plural': 'Медицины'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
